spring:
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      datasource:
        master:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://47.100.92.144:3316/education_account?characterEncoding=utf8&useSSL=false
          druid:
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall
            share-prepared-statements: true
          slave:
            one:
              username: root
              password: root
              driver-class-name: com.mysql.jdbc.Driver
              url: jdbc:mysql://47.100.92.144:3317/education_account?characterEncoding=utf8&useSSL=false
            two:
              username: root
              password: root
              driver-class-name: com.mysql.jdbc.Driver
              url: jdbc:mysql://47.100.92.144:3318/education_account?characterEncoding=utf8&useSSL=false



logging:
  level:
    com.example.demo.mapper: debug

server:
  port: 8080

mybatis-plus:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.vip.demo1.domain.entity
    global-config:
      db-config:
        id-type: auto
        table-underline: true
        logic-not-delete-value: 0
        logic-delete-value: 1
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      jdbc-type-for-null: null
